services:
    wandi.easy_admin_plus.command.user.create:
          class: Wandi\EasyAdminPlusBundle\Auth\Command\UserCreateCommand
          tags:
              -  { name: console.command, command: wandi:easy-admin-plus:user:create }
    wandi.easy_admin_plus.command.user.remove:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserRemoveCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:remove }
    wandi.easy_admin_plus.command.user.change_password:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserChangePasswordCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:change-password }
    wandi.easy_admin_plus.command.user.enable:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserEnableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:enable }
    wandi.easy_admin_plus.command.user.disable:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserDisableCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:disable }
    wandi.easy_admin_plus.command.user.add_roles:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserAddRolesCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:add-roles }
    wandi.easy_admin_plus.command.user.remove_roles:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserRemoveRolesCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:remove-roles }
    wandi.easy_admin_plus.command.user.set_roles:
        class: Wandi\EasyAdminPlusBundle\Auth\Command\UserSetRolesCommand
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:user:set-roles }

    wandi.easy_admin_plus.translator:
        class: Wandi\EasyAdminPlusBundle\Translator\Translator
        public: true
        arguments:
            - '%easy_admin_plus%'
            - '%kernel.cache_dir%'

    wandi.easy_admin_plus.acl.security.admin_authorization_checker:
        class: Wandi\EasyAdminPlusBundle\Acl\Security\AdminAuthorizationChecker
        public: true
        arguments:
            - '@security.authorization_checker'
    wandi.easy_admin_plus.acl.event_listener.easy_admin_subscriber:
        class: Wandi\EasyAdminPlusBundle\Acl\EventListener\EasyAdminSubscriber
        arguments:
            - '@wandi.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: kernel.event_subscriber }
    wandi.easy_admin_plus.acl.twig.admin_authorization_extension:
        class: Wandi\EasyAdminPlusBundle\Acl\Twig\AdminAuthorizationExtension
        arguments:
            - '@wandi.easy_admin_plus.acl.security.admin_authorization_checker'
        tags:
            - { name: twig.extension }
    wandi.easy_admin_plus.exporter.configuration.normalizer_config_pass:
        class: Wandi\EasyAdminPlusBundle\Exporter\Configuration\NormalizerConfigPass
    wandi.easy_admin_plus.exporter.configuration.property_config_pass:
        class: Wandi\EasyAdminPlusBundle\Exporter\Configuration\PropertyConfigPass
    wandi.easy_admin_plus.exporter.configuration.template_config_pass:
        class: Wandi\EasyAdminPlusBundle\Exporter\Configuration\TemplateConfigPass

    wandi.easy_admin_plus.generator.base:
        abstract: true
        autowire: true

    wandi.easy_admin_plus.generator.entity.creation:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\EntityCreation
        arguments:
            - '@wandi.easy_admin_plus.generator.method.creation'
            - '@wandi.easy_admin_plus.generator.entity.properties.creation'
        autowire: true

    wandi.easy_admin_plus.generator.method.creation:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\MethodCreation
        arguments:
            - '@wandi.easy_admin_plus.generator.field.creation'
        autowire: true

    wandi.easy_admin_plus.generator.field.creation:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\FieldCreation

    wandi.easy_admin_plus.generator.entity.properties.creation:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\EntityPropertiesCreation
        autowire: true

    wandi.easy_admin_plus.generator.clean:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorClean
        parent: wandi.easy_admin_plus.generator.base
    wandi.easy_admin_plus.generator.entity:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorEntity
        parent: wandi.easy_admin_plus.generator.base
    wandi.easy_admin_plus.generator.generate:
        class: Wandi\EasyAdminPlusBundle\Generator\Service\GeneratorGenerate
        arguments:
            - '@wandi.easy_admin_plus.generator.entity.creation'
        parent: wandi.easy_admin_plus.generator.base
    wandi.easy_admin_plus.command.generator.clean:
        class: Wandi\EasyAdminPlusBundle\Generator\Command\GeneratorCleanCommand
        arguments:
            - '@wandi.easy_admin_plus.generator.clean'
            - '%kernel.project_dir%'
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:generator:cleanup }
    wandi.easy_admin_plus.command.generator.entity:
        class: Wandi\EasyAdminPlusBundle\Generator\Command\GeneratorEntityCommand
        arguments:
            - '@wandi.easy_admin_plus.generator.entity'
            - '@doctrine.orm.entity_manager'
            - '%kernel.project_dir%'
        tags:
            -  { name: console.command, command: wandi:easy-admin-plus:generator:entity }
    wandi.easy_admin_plus.command.generator.generate:
        class: Wandi\EasyAdminPlusBundle\Generator\Command\GeneratorGenerateCommand
        autowire: true
        arguments:
            - '@wandi.easy_admin_plus.generator.generate'
            - '%kernel.project_dir%'
        tags:
            - { name: console.command, command: wandi:easy-admin-plus:generator:generate }

